language: node_js
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
  - '0.8'

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@2'
